### PR TITLE
publish docs nightly

### PR DESCRIPTION
**Pull request by pjfanning**
link-validator CI job is failing due to connectivity issues with git.io and I think it can be ignored for today

### CODE REVIEW

**Review by mdedetrich — CHANGES_REQUESTED** [review]
There is already a publish job for this project, it just does it after PR merge and not nightly

https://github.com/apache/incubator-pekko-persistence-jdbc/blob/main/.github/workflows/publish.yml

**Comment by pjfanning** [comment]
> There is already a publish job for this project, it just does it after PR merge and not nightly
> 
> https://github.com/apache/incubator-pekko-persistence-jdbc/blob/main/.github/workflows/publish.yml

My publish-nightly just publishes docs. Should I get rid of the after commit publish job and merge its publishing of jars work into publish-nightly? That is more consistent with what we do elsewhere.

**Comment by mdedetrich** [comment]
> My publish-nightly just publishes docs. Should I get rid of the after commit publish job and merge its publishing of jars work into publish-nightly? That is more consistent with what we do elsewhere.

Yes, lets make the publishing nightly consistent with the rest of the other pekko modules. We can always change this later to make it consistent

**Comment by pjfanning** [comment]
@mdedetrich are the latest changes ok?

**Review by mdedetrich — APPROVED** [review]
Lgtm

**Pull request merged**
