### PR TITLE
upgrade cache-action

### PR DESCRIPTION
**Pull request by pjfanning**
relates to https://github.com/apache/incubator-pekko/pull/42

### CODE REVIEW

**Comment by pjfanning** [comment]
@mdedetrich I fixed a few CI issues. That scala format test fails but I'm aware that this is an area that you have been trying to change - so I thought I'd leave that alone.

**Comment by mdedetrich** [comment]
@pjfanning If you want the test to quickly pass for now you can just run `scalafmtSbt` locally, the issue seems to be that the `build.sbt` is not formatted.

**Comment by pjfanning** [comment]
> @pjfanning If you want the test to quickly pass for now you can just run `sbt scalafmtSbt` locally, the issue seems to be that the `build.sbt` is not formatted.
> 
> Otherwise we can just approve and merge.

Thanks @mdedetrich - I ran the reformat and the build is clean now

**Review by mdedetrich — APPROVED** [review]
lgtm

**Pull request merged**
