### PR TITLE
pekko naming

### PR DESCRIPTION
**Pull request by pjfanning**
* uptake upstream pekko jars
* change package names away from akka
* change config names to start with pekko
* some doc updates

### CODE REVIEW

**Review by nvollmar — APPROVED** [review]
lgtm

**Review by nvollmar — APPROVED** [review]
lgtm

**Comment by pjfanning** [comment]
merging - the test failure looks like an intermittent issue

**Comment by nvollmar** [comment]
> merging - the test failure looks like an intermittent issue

From previous contributions I know those are somewhat flacky

**Pull request merged**
